name: Streamlit Build

on:
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    env:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_REGION: ${{ secrets.GCP_REGION }}
      ARTIFACT_REGISTRY: ${{ secrets.ARTIFACT_DASHBOARD }}
      IMAGE_NAME: sales-forecast-dashboard

    defaults:
      run:
        working-directory: streamlit

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Auth (explicit)
        run: |
          echo "${{ secrets.GCP_SA_KEY_B64 }}" | base64 -d > /tmp/key.json
          gcloud auth activate-service-account --key-file=/tmp/key.json --project="${{ secrets.GCP_PROJECT_ID }}"

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker asia-northeast1-docker.pkg.dev --quiet

      - name: Build Docker image
        run: |
          docker build --no-cache -t $ARTIFACT_REGISTRY/$IMAGE_NAME:latest .

      - name: Push Docker image to Artifact Registry
        run: |
          docker push $ARTIFACT_REGISTRY/$IMAGE_NAME:latest
