name: VertexAI Train

on:
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    env:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_REGION: ${{ secrets.GCP_REGION }}
      ARTIFACT_REGISTRY: ${{ secrets.ARTIFACT_REGISTRY }}
      IMAGE_NAME: vertexai-train

    defaults:
      run:
        working-directory: vertexai/learning

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Auth (explicit)
        run: |
          echo "${{ secrets.GCP_SA_KEY_B64 }}" | base64 -d > /tmp/key.json
          gcloud auth activate-service-account --key-file=/tmp/key.json --project="${{ secrets.GCP_PROJECT_ID }}"

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker asia-northeast1-docker.pkg.dev --quiet

      - name: Build Docker image
        run: |
          docker build -t $ARTIFACT_REGISTRY/$IMAGE_NAME:latest .

      - name: Push Docker image to Artifact Registry
        run: |
          docker push $ARTIFACT_REGISTRY/$IMAGE_NAME:latest

  vertexai-custom-job:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    env:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_REGION: ${{ secrets.GCP_REGION }}
      ARTIFACT_REGISTRY: ${{ secrets.ARTIFACT_REGISTRY }}
      IMAGE_NAME: vertexai-train
      BQ_TABLE: ${{ secrets.BQ_TABLE }}
      MODEL_PATH: ${{ secrets.MODEL_PATH }}

    defaults:
      run:
        working-directory: vertexai/learning

    steps:
      - name: Auth (explicit)
        run: |
          echo "${{ secrets.GCP_SA_KEY_B64 }}" | base64 -d >  /tmp/key.json
          gcloud auth activate-service-account --key-file=/tmp/key.json --project="${{ secrets.GCP_PROJECT_ID }}"
      - name: Run VertexAI Custom Job
        run: |
          gcloud ai custom-jobs create \
            --region=$GCP_REGION \
            --display-name=vertexai-train-job \
            --worker-pool-spec=machine-type=n1-standard-4,replica-count=1,container-image-uri=$ARTIFACT_REGISTRY/$IMAGE_NAME:latest \
            --command=python \
            --args=train.py,--bq_table=$BQ_TABLE,--model_path=$MODEL_PATH
