name: VertexAI Train

on:
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    env:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_REGION: ${{ secrets.GCP_REGION }}
      ARTIFACT_REGISTRY: ${{ secrets.ARTIFACT_REGISTRY }}
      IMAGE_NAME: vertexai-train

    defaults:
      run:
        working-directory: vertexai/learning

    steps:
      - uses: actions/checkout@v4

      - name: Auth (explicit)
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" > /tmp/key.json
          gcloud auth activate-service-account --key-file=/tmp/key.json --project="${{ secrets.GCP_PROJECT_ID }}"
          gcloud auth list

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker asia-northeast1-docker.pkg.dev --quiet

      - name: Build image
        run: |
          docker build -t $ARTIFACT_REGISTRY/$IMAGE_NAME:latest .

      - name: Push
        run: |
          docker push $ARTIFACT_REGISTRY/$IMAGE_NAME:latest
